dataset = {
    "SHANKAR D": {
    "city": 2,
    "movies": 5,
    "sports": 1,
    "salary": 2,
    "age": 1,
    "marriage": 1,
    "klout": 1,
    "vehicle": 1,
    "politically": 2,
    "auto": 1,
    "work": 4
  },
  "DEVABHAI KALABHAI ALGOTTAR": {
    "city": 2,
    "movies": 5,
    "sports": 3,
    "salary": 5,
    "age": 2,
    "marriage": 1,
    "klout": 2,
    "vehicle": 3,
    "politically": 3,
    "auto": 4,
    "work": 3
  },
  "DIPITMAN BOSE ": {
    "city": 3,
    "movies": 5,
    "sports": 1,
    "salary": 5,
    "age": 3,
    "marriage": 1,
    "klout": 3,
    "vehicle": 4,
    "politically": 4,
    "auto":2,
    "work": 2
  },
  "DATTADIP MADHU NAGVEKAR": {
    "city": 3,
    "movies": 5,
    "sports": 5,
    "salary": 2,
    "age": 1,
    "marriage": 1,
    "klout": 1,
    "vehicle": 2,
    "politically": 4,
    "auto": 1,
    "work": 2
  },
  "SHISHUPAL YADAV": {
    "city": 3,
    "movies": 2,
    "sports": 3,
    "salary": 2,
    "age": 2,
    "marriage": 2,
    "klout": 2,
    "vehicle": 2,
    "politically": 3,
    "auto": 5,
    "work": 4
  },
  "SHAKEEL AHMAD": {
    "city": 1,
    "movies": 5,
    "sports": 1,
    "salary": 2,
    "age": 1,
    "marriage": 1,
    "klout": 1,
    "vehicle": 3,
    "politically": 2,
    "auto": 2,
    "work": 2
  },
  "SATISH KUMAR ": {
    "city": 2,
    "movies": 3,
    "sports": 3,
    "salary": 1,
    "age": 3,
    "marriage": 2,
    "klout": 1,
    "vehicle": 4,
    "politically": 3,
    "auto": 1,
    "work": 5
  }
}
